import type { Metadata } from "next";
import localFont from 'next/font/local';

import "./styles/globals.scss";

import "./styles/abstracts/_breakpoints.scss";
import "./styles/abstracts/_colors.scss";
import "./styles/abstracts/_radius.scss";
import "./styles/abstracts/_shadows.scss";
import "./styles/abstracts/_spacing.scss";
import "./styles/abstracts/_typography.scss";
import "./styles/base/_typography.scss";

import "./styles/components/_button.scss";
import "./styles/components/_card.scss";


import "./styles/layout/_container.scss";
import "./styles/layout/_grid.scss";
import "./styles/layout/_section.scss";


import "./styles/layout/_section.scss";

import "./styles/components/navbar.scss";
import "./styles/components/whatsapp.scss";

import CTAFooter from "@/components/sections/CTAFooter";
import Navbar from "@/components/ui/Navbar";


const Urbanist = localFont({
  src: [
    {
      path: './fonts/Urbanist-Black.ttf',
      weight: '800',
      style: 'normal',
    },
    {
      path: './fonts/Urbanist-ExtraBold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Urbanist-Bold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/Urbanist-SemiBold.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Urbanist-Medium.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Urbanist-Regular.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/Urbanist-Light.ttf',
      weight: '200',
      style: 'normal',
    },
    {
      path: './fonts/Urbanist-Thin.ttf',
      weight: '100',
      style: 'normal',
    },
  ],
  variable: '--font-Urbanist',
  display: 'swap',
});

const Inter = localFont({
  src: [
    {
      path: './fonts/Inter-Black.ttf',
      weight: '800',
      style: 'normal',
    },
    {
      path: './fonts/Inter-ExtraBold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Inter-Bold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/Inter-SemiBold.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Inter-Medium.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Inter-Regular.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/Inter-Light.ttf',
      weight: '200',
      style: 'normal',
    },
    {
      path: './fonts/Inter-Thin.ttf',
      weight: '100',
      style: 'normal',
    },
  ],
  variable: '--font-Inter',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "REAL ESTATE - Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${Inter.variable} ${Urbanist.variable} antialiased`}
    >
      <body>
        <Navbar />
          {children}
        <div className="section-no-padding">
          <div className="container-no-padding">
            <CTAFooter />
          </div>
        </div>
      </body>
    </html>
  );
}
